name: Release (Stable)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    uses: ./.github/workflows/package-release.yml
    with:
      prerelease: false
    secrets:
      tizen-author-p12: ${{ secrets.TIZEN_AUTHOR_P12_BASE64 }}
